security:
  oauth2:
    resource:
      token-info-uri: https://oidc-ver2.difi.no/idporten-oidc-provider/tokeninfo

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
server.port: 4500
spring.jpa.hibernate.ddl-auto: none
spring.datasource.url:jdbc:mysql: //10.243.202.65/dc17_IDPevent
spring.datasource.username: DC17
spring.datasource.password: Helgheim
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.jpa.show-sql: true